USE api_rest;

-- Tabela de usuários
CREATE TABLE IF NOT EXISTS users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50) UNIQUE,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de boards (quadros)
CREATE TABLE IF NOT EXISTS boards (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	creator_id INT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (creator_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Tabela de colunas
CREATE TABLE IF NOT EXISTS columns (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	board_id INT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE CASCADE
);

-- Tabela de cards
CREATE TABLE IF NOT EXISTS cards (
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(50) NOT NULL,
	content VARCHAR(200),
	column_id INT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (column_id) REFERENCES columns(id) ON DELETE CASCADE
);

-- Tabela de participantes dos cards
CREATE TABLE IF NOT EXISTS participants_card (
	user_id INT NOT NULL,
	card_id INT NOT NULL,
	added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (card_id) REFERENCES cards(id) ON DELETE CASCADE,
	PRIMARY KEY (user_id, card_id)
);

-- Tabela de participantes dos boards
CREATE TABLE IF NOT EXISTS participantes_board (
	user_id INT NOT NULL,
	board_id INT NOT NULL,
	added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE CASCADE,
	PRIMARY KEY (user_id, board_id)
);